openapi: 3.0.1
info:
  contact:
    email: anton.perhunov@aspose.com
    name: GroupDocs
    url: https://products.groupdocs.cloud/rewriter/
  license:
    name: Aspose EULA
    url: https://about.aspose.com/legal/eula/
  termsOfService: https://about.groupdocs.cloud/legal/tos/
  title: GroupDocs.Rewriter API
  version: 23.11.1
servers:
- url: https://api.groupdocs.cloud/v2.0/rewriter
paths:
  /detect/document:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectionFileRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ detecting."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Detect paraphrasing in the document
      tags:
      - Detect
  /detect/text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DetectionTextRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ detection."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Detect paraphrasing in text
      tags:
      - Detect
  /detect/document/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/document response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DetectionFileResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/DetectionFileResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/DetectionFileResponse'
          description: Success
      summary: "Return document detection status.\r\nAlso return probability of paraphrasing\
        \ for the whole document and per paragraph"
      tags:
      - Detect
  /detect/text/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/document response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DetectionTextResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/DetectionTextResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/DetectionTextResponse'
          description: Success
      summary: "Return text detection status.\r\nAlso return probability of paraphrasing\
        \ for the whole text"
      tags:
      - Detect
  /detect/hc:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success
      summary: Health check for detect all services.
      tags:
      - Detect
  /paraphrase/document:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParaphraseFileRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ rewriting."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Rewrite document
      tags:
      - Paraphrase
  /paraphrase/text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParaphraseTextRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ rewriting."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Rewrite text
      tags:
      - Paraphrase
  /paraphrase/document/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/document response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ParaphraseFileResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ParaphraseFileResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ParaphraseFileResponse'
          description: Success
      summary: "Return document rewriting status.\r\nAlso return URLs for downloading\
        \ of rewritten document if paraphrasig was successful"
      tags:
      - Paraphrase
  /paraphrase/text/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/text response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ParaphraseTextResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/ParaphraseTextResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ParaphraseTextResponse'
          description: Success
      summary: "Return text rewriting status.\r\nAlso return rewritten text if paraphrasing\
        \ was successful"
      tags:
      - Paraphrase
  /paraphrase/hc:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success
      summary: Health check for all paraphrase services.
      tags:
      - Paraphrase
  /paraphrase/supportedConversions:
    get:
      parameters:
      - explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          - Md
          - Html
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            application/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            text/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
          description: Success
      tags:
      - Paraphrase
  /simplify/document:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimplifyFileRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ simplifying."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Simplify document
      tags:
      - Simplify
  /simplify/text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BaseTextRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ simplifying."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Simplify text
      tags:
      - Simplify
  /simplify/document/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/document response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SimplifyFileResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SimplifyFileResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SimplifyFileResponse'
          description: Success
      summary: "Return document simplifying status.\r\nAlso return URLs for downloading\
        \ of simplified document if paraphrasig was successful"
      tags:
      - Simplify
  /simplify/text/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/text response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SimplifyTextResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SimplifyTextResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SimplifyTextResponse'
          description: Success
      summary: "Return text simplifying status.\r\nAlso return simplified text if\
        \ paraphrasing was successful"
      tags:
      - Simplify
  /simplify/hc:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success
      summary: Health check for all simplify services.
      tags:
      - Simplify
  /simplify/supportedConversions:
    get:
      parameters:
      - explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          - Md
          - Html
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            application/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            text/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
          description: Success
      tags:
      - Simplify
  /summarize/document:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizationFileRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ summarizing."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Summarize document
      tags:
      - Summarize
  /summarize/text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SummarizationTextRequest'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Summarize text
      tags:
      - Summarize
  /summarize/document/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/document response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SummarizationFileResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizationFileResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SummarizationFileResponse'
          description: Success
      summary: "Return document summarizing status.\r\nAlso return URLs for downloading\
        \ of summarized document if summarization was successful"
      tags:
      - Summarize
  /summarize/text/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/text response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SummarizationTextResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SummarizationTextResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SummarizationTextResponse'
          description: Success
      summary: "Return text summarizing status status.\r\nAlso return rewrote text\
        \ if translation was successful"
      tags:
      - Summarize
  /summarize/hc:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success
      summary: Health check for all summarize services.
      tags:
      - Summarize
  /summarize/supportedConversions:
    get:
      parameters:
      - explode: true
        in: query
        name: format
        required: false
        schema:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          - Md
          - Html
          type: string
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            application/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
            text/json:
              schema:
                items:
                  enum:
                  - Docx
                  - Rtf
                  - Html
                  - Odt
                  - Txt
                  - Md
                  - Pdf
                  - Tiff
                  - Svg
                  - Xps
                  - Pptx
                  - Git
                  type: string
                type: array
          description: Success
      tags:
      - Summarize
  /synonymize/text:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SynonymizeTextRequest'
        description: "String in body of request, containing JSON with parameters for\
          \ synonymizing."
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
      summary: Synonymize word
      tags:
      - Synonymize
  /synonymize/text/{requestId}:
    get:
      parameters:
      - description: GUID which got from /v3/rewriter/text response
        explode: false
        in: path
        name: requestId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/SynonymizeTextResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/SynonymizeTextResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/SynonymizeTextResponse'
          description: Success
      summary: "Return text synonymizing status.\r\nAlso return list of synonyms if\
        \ it was successful"
      tags:
      - Synonymize
  /synonymize/hc:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'
          description: Success
      summary: Health check for all synonymizer services.
      tags:
      - Synonymize
components:
  schemas:
    BaseTextRequest:
      additionalProperties: false
      example:
        texts:
        - texts
        - texts
        origin: origin
        language: language
        text: text
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        text:
          description: Single text paragraph
          type: string
        texts:
          description: Text paragraphs
          items:
            type: string
          type: array
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
      required:
      - language
      type: object
    CloudTextRequest:
      additionalProperties: false
      example:
        diversity: 1
        texts:
        - texts
        - texts
        requestId: requestId
        origin: origin
        action: action
        language: 0
        suggestions: 6
        text: text
        tokenize: true
      properties:
        language:
          description: Language of original text
          format: int32
          type: integer
        text:
          description: Text to rewrite
          type: string
        action:
          description: Rewrite or summarize
          type: string
        texts:
          description: Text array to rewrite
          items:
            type: string
          type: array
        suggestions:
          description: "Number of suggested variants, 3 maximum"
          format: int32
          type: integer
        diversity:
          description: Diversity of text
          format: int32
          type: integer
        tokenize:
          description: Should source and target texts be returned in tokenized form
          type: boolean
        origin:
          description: for analysis only
          type: string
        requestId:
          type: string
      type: object
    DegreeEnum:
      enum:
      - "Off"
      - Medium
      - High
      type: string
    DetectionFileRequest:
      additionalProperties: false
      example:
        originalName: originalName
        file: file
        origin: origin
        savingMode: null
        minLength: 0
        format: Unknown
        language: language
        url: url
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        file:
          description: Source file format
          format: byte
          type: string
        url:
          type: string
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        originalName:
          type: string
        savingMode:
          $ref: '#/components/schemas/FileSavingMode'
        minLength:
          format: int32
          type: integer
        format:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          type: string
      required:
      - language
      type: object
    DetectionFileResponse:
      additionalProperties: false
      example:
        probability: 0.8008282
        perParagraphProbability:
        - 6.0274563
        - 6.0274563
        isParaphrased: true
        message: message
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        probability:
          description: The probability that the text turned out to be paraphrased
          format: float
          type: number
        isParaphrased:
          type: boolean
        perParagraphProbability:
          items:
            format: float
            type: number
          type: array
      type: object
    DetectionTextRequest:
      additionalProperties: false
      example:
        texts:
        - texts
        - texts
        origin: origin
        language: language
        text: text
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        text:
          description: Single text paragraph
          type: string
        texts:
          description: Text paragraphs
          items:
            type: string
          type: array
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
      required:
      - language
      type: object
    DetectionTextResponse:
      additionalProperties: false
      example:
        probability: 0.8008282
        isParaphrased: true
        message: message
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        probability:
          description: The probability that the text turned out to be paraphrased
          format: float
          type: number
        isParaphrased:
          type: boolean
      type: object
    FileSavingMode:
      enum:
      - Files
      - Archive
      - Both
      type: string
    HealthCheckInfo:
      additionalProperties: false
      example:
        filesProcessorStatus: filesProcessorStatus
        summarizationStatus: summarizationStatus
        detectorStatus: detectorStatus
        paraphrasingStatus: paraphrasingStatus
      properties:
        filesProcessorStatus:
          type: string
        paraphrasingStatus:
          type: string
        detectorStatus:
          type: string
        summarizationStatus:
          type: string
      type: object
    HealthCheckResponse:
      additionalProperties: false
      example:
        models:
        - loaded: true
          models:
          - models
          - models
          opt:
            beam_size: 5
            gpu: 2
            replace_unk: true
          models_id: 5
          timeout: 7
          tokenizer:
            model: model
            type: type
        - loaded: true
          models:
          - models
          - models
          opt:
            beam_size: 5
            gpu: 2
            replace_unk: true
          models_id: 5
          timeout: 7
          tokenizer:
            model: model
            type: type
        healthCheckInfo:
          filesProcessorStatus: filesProcessorStatus
          summarizationStatus: summarizationStatus
          detectorStatus: detectorStatus
          paraphrasingStatus: paraphrasingStatus
        initialRequest:
          diversity: 1
          texts:
          - texts
          - texts
          requestId: requestId
          origin: origin
          action: action
          language: 0
          suggestions: 6
          text: text
          tokenize: true
      properties:
        initialRequest:
          $ref: '#/components/schemas/CloudTextRequest'
        healthCheckInfo:
          $ref: '#/components/schemas/HealthCheckInfo'
        models:
          items:
            $ref: '#/components/schemas/Model'
          type: array
      type: object
    HttpStatusCode:
      enum:
      - Continue
      - SwitchingProtocols
      - Processing
      - EarlyHints
      - OK
      - Created
      - Accepted
      - NonAuthoritativeInformation
      - NoContent
      - ResetContent
      - PartialContent
      - MultiStatus
      - AlreadyReported
      - IMUsed
      - MultipleChoices
      - MovedPermanently
      - Found
      - SeeOther
      - NotModified
      - UseProxy
      - Unused
      - TemporaryRedirect
      - PermanentRedirect
      - BadRequest
      - Unauthorized
      - PaymentRequired
      - Forbidden
      - NotFound
      - MethodNotAllowed
      - NotAcceptable
      - ProxyAuthenticationRequired
      - RequestTimeout
      - Conflict
      - Gone
      - LengthRequired
      - PreconditionFailed
      - RequestEntityTooLarge
      - RequestUriTooLong
      - UnsupportedMediaType
      - RequestedRangeNotSatisfiable
      - ExpectationFailed
      - MisdirectedRequest
      - UnprocessableEntity
      - Locked
      - FailedDependency
      - UpgradeRequired
      - PreconditionRequired
      - TooManyRequests
      - RequestHeaderFieldsTooLarge
      - UnavailableForLegalReasons
      - InternalServerError
      - NotImplemented
      - BadGateway
      - ServiceUnavailable
      - GatewayTimeout
      - HttpVersionNotSupported
      - VariantAlsoNegotiates
      - InsufficientStorage
      - LoopDetected
      - NotExtended
      - NetworkAuthenticationRequired
      type: string
    Model:
      additionalProperties: false
      example:
        loaded: true
        models:
        - models
        - models
        opt:
          beam_size: 5
          gpu: 2
          replace_unk: true
        models_id: 5
        timeout: 7
        tokenizer:
          model: model
          type: type
      properties:
        loaded:
          type: boolean
        models_id:
          format: int32
          type: integer
        models:
          items:
            type: string
          type: array
        opt:
          $ref: '#/components/schemas/Opt'
        timeout:
          format: int32
          type: integer
        tokenizer:
          $ref: '#/components/schemas/Tokenizer'
      type: object
    Opt:
      additionalProperties: false
      example:
        beam_size: 5
        gpu: 2
        replace_unk: true
      properties:
        beam_size:
          format: int32
          type: integer
        gpu:
          format: int32
          type: integer
        replace_unk:
          type: boolean
      type: object
    ParaphraseFileRequest:
      additionalProperties: false
      example:
        originalName: originalName
        file: file
        diversityDegree: null
        origin: origin
        savingMode: null
        format: Unknown
        language: language
        outputFormat: null
        url: url
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        file:
          description: Source file format
          format: byte
          type: string
        url:
          type: string
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        originalName:
          type: string
        savingMode:
          $ref: '#/components/schemas/FileSavingMode'
        outputFormat:
          $ref: '#/components/schemas/SupportedConversionsFormats'
        diversityDegree:
          $ref: '#/components/schemas/DegreeEnum'
        format:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          - Md
          - Html
          type: string
      required:
      - language
      - outputFormat
      type: object
    ParaphraseFileResponse:
      additionalProperties: false
      example:
        message: message
        url: url
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        url:
          type: string
      type: object
    ParaphraseTextRequest:
      additionalProperties: false
      example:
        texts:
        - texts
        - texts
        diversityDegree: null
        origin: origin
        language: language
        suggestions: One
        text: text
        tokenize: true
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        text:
          description: Single text paragraph
          type: string
        texts:
          description: Text paragraphs
          items:
            type: string
          type: array
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        suggestions:
          description: Number of variants for rewriting
          enum:
          - One
          - Two
          - Three
          type: string
        diversityDegree:
          $ref: '#/components/schemas/DegreeEnum'
        tokenize:
          description: Determines whether to return a tokens list
          type: boolean
      required:
      - language
      type: object
    ParaphraseTextResponse:
      additionalProperties: false
      example:
        targetList:
        - targetList
        - targetList
        sourceList:
        - sourceList
        - sourceList
        paraphraseReult: paraphraseReult
        paraphraseResults:
        - paraphraseResults
        - paraphraseResults
        message: message
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        paraphraseReult:
          nullable: true
          type: string
        paraphraseResults:
          items:
            type: string
          nullable: true
          type: array
        sourceList:
          description: Return tokenized source text
          items:
            type: string
          nullable: true
          type: array
        targetList:
          description: Return tokenized target text
          items:
            type: string
          nullable: true
          type: array
      type: object
    SimplifyFileRequest:
      additionalProperties: false
      example:
        originalName: originalName
        file: file
        origin: origin
        savingMode: null
        format: Unknown
        language: language
        outputFormat: null
        url: url
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        file:
          description: Source file format
          format: byte
          type: string
        url:
          type: string
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        originalName:
          type: string
        savingMode:
          $ref: '#/components/schemas/FileSavingMode'
        outputFormat:
          $ref: '#/components/schemas/SupportedConversionsFormats'
        format:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          - Md
          - Html
          type: string
      required:
      - language
      - outputFormat
      type: object
    SimplifyFileResponse:
      additionalProperties: false
      example:
        message: message
        url: url
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        url:
          type: string
      type: object
    SimplifyTextResponse:
      additionalProperties: false
      example:
        simplifyResults:
        - simplifyResults
        - simplifyResults
        message: message
        simplifyReult: simplifyReult
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        simplifyReult:
          nullable: true
          type: string
        simplifyResults:
          items:
            type: string
          nullable: true
          type: array
      type: object
    StatusResponse:
      additionalProperties: false
      example:
        id: id
        message: message
        status: null
      properties:
        status:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          type: string
        id:
          type: string
      type: object
    SummarizationFileRequest:
      additionalProperties: false
      example:
        originalName: originalName
        summarizationDegree: null
        file: file
        origin: origin
        savingMode: null
        minLength: 0
        format: Unknown
        language: language
        outputFormat: null
        url: url
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        file:
          description: Source file format
          format: byte
          type: string
        url:
          type: string
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        originalName:
          type: string
        savingMode:
          $ref: '#/components/schemas/FileSavingMode'
        outputFormat:
          $ref: '#/components/schemas/SupportedConversionsFormats'
        summarizationDegree:
          $ref: '#/components/schemas/DegreeEnum'
        minLength:
          description: Minimum length of the target text
          format: int32
          type: integer
        format:
          enum:
          - Unknown
          - Doc
          - Docx
          - Docm
          - Rtf
          - Odt
          - Txt
          - Pdf
          type: string
      required:
      - language
      - outputFormat
      type: object
    SummarizationFileResponse:
      additionalProperties: false
      example:
        message: message
        url: url
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        url:
          type: string
      type: object
    SummarizationTextRequest:
      additionalProperties: false
      example:
        summarizationDegree: null
        texts:
        - texts
        - texts
        origin: origin
        language: language
        text: text
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        text:
          description: Single text paragraph
          type: string
        texts:
          description: Text paragraphs
          items:
            type: string
          type: array
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        summarizationDegree:
          $ref: '#/components/schemas/DegreeEnum'
      required:
      - language
      type: object
    SummarizationTextResponse:
      additionalProperties: false
      example:
        summarizationResults:
        - summarizationResults
        - summarizationResults
        summarizationResult: summarizationResult
        message: message
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        summarizationResult:
          nullable: true
          type: string
        summarizationResults:
          items:
            type: string
          nullable: true
          type: array
      type: object
    SupportedConversionsFormats:
      enum:
      - Docx
      - Rtf
      - Html
      - Odt
      - Txt
      - Md
      - Pdf
      - Tiff
      - Svg
      - Xps
      - Pptx
      - Git
      type: string
    SynonymizeTextRequest:
      additionalProperties: false
      example:
        texts:
        - texts
        - texts
        synonyms: All
        origin: origin
        language: language
        text: text
      properties:
        language:
          description: Set language of text
          minLength: 1
          type: string
        text:
          description: Single text paragraph
          type: string
        texts:
          description: Text paragraphs
          items:
            type: string
          type: array
        origin:
          description: "Information about SDK user, like a User-Agent"
          type: string
        synonyms:
          description: Number of variants for rewriting
          enum:
          - All
          - One
          - Two
          - Three
          - Four
          - Five
          type: string
      required:
      - language
      type: object
    SynonymizeTextResponse:
      additionalProperties: false
      example:
        synonymizerResults:
        - synonymizerResults
        - synonymizerResults
        message: message
        statusCode: null
      properties:
        statusCode:
          $ref: '#/components/schemas/HttpStatusCode'
        message:
          description: Information about process
          type: string
        synonymizerResults:
          items:
            type: string
          type: array
      type: object
    Tokenizer:
      additionalProperties: false
      example:
        model: model
        type: type
      properties:
        model:
          type: string
        type:
          type: string
      type: object
  securitySchemes:
    JWT:
      description: Please enter APP SID & KEY
      flows:
        clientCredentials:
          scopes: {}
          tokenUrl: https://id.groupdocs.cloud/connect/token
      type: oauth2

